name: build
on:
  push:
    branches:
    - main
    - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Build
    outputs:
      semver: ${{ steps.run_build.outputs.SemVer }}
      major: ${{ steps.run_build.outputs.Major }}
      majorMinor: ${{ steps.run_build.outputs.Major }}.${{ steps.run_build.outputs.Minor }}
      preReleaseTag: ${{ steps.run_build.outputs.PreReleaseTag }}
    steps:
    # Setup steps
    - uses: actions/setup-dotnet@v1
      if: ${{ github.actor != 'nektos/act' }}
      name: Install .NET Core SDK 6.0.x
      with:
        dotnet-version: '6.0.x'

    # Build steps
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - id: azlogin_test
      name: Azure Login (TEST)
      uses: azure/login@v1
      with:
        creds: ${{ secrets.ENDJIN_TEST_ACR_PUBLISH_CREDENTIALS }}
    - id: run_build
      name: Build & Publish Bicep Modules to Test Registry
      run: |
        pwsh -f ./build.ps1 -Task FullBuildAndPublish

    # Final Publish steps
    - id: azlogin_prod
      name: Azure Login (PROD)
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: azure/login@v1
      with:
        creds: ${{ secrets.ENDJIN_PROD_ACR_PUBLISH_CREDENTIALS }}
    - id: publish_to_prod
      name: Publish Bicep Modules to Prod Registry
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        pwsh -f ./build.ps1 -Task PublishBicepModules
      env:
        BUILDVAR_BicepRegistryFqdn: endjin.azurecr.io
        BUILDVAR_BaseBranch: 'HEAD~1'
        PublicRelease: true

